# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "tests"
  tests:
    name: tests
    strategy:
      matrix:
        pyver: [3.6, 3.7, 3.8]
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge,defaults
          channel-priority: strict
          show-channel-urls: true
          
      # Runs a set of commands using the runners shell
      - name: configure conda and install code
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install --quiet \
            pip \
            setuptools \
            numpy \
            numba \
            flake8 \
            pyyaml \
            scipy \
            pytest \
            galsim \
            tensorflow
            
          python -m pip install -e .
          
      - name: test
        shell: bash -l {0}
        run: |
          pytest 
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
